jungsae/Well-Com

.gitignore

[ADD] gitignore

---

front-end/package-lock.json
front-end/src/components/LoginComponent.vue
front-end/src/components/ParentComponent.vue
front-end/src/components/SignInComponent.vue
front-end/src/components/SignUpComponent.vue
front-end/src/router/index.js
src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
src/main/java/com/wellcom/global/config/SecurityConfig.java
src/main/java/com/wellcom/global/jwt/filter/JwtAuthenticationProcessingFilter.java
src/main/java/com/wellcom/global/jwt/service/JwtService.java
src/main/java/com/wellcom/global/login/handler/LoginSuccessHandler.java

[HOTFIX] 급합니다.

---

.settings/org.eclipse.buildship.core.prefs
src/main/java/com/wellcom/domain/Desk/Desk.java
src/main/java/com/wellcom/domain/Item/Item.java
src/main/java/com/wellcom/domain/Item/ItemStatus.java
src/main/java/com/wellcom/domain/Item/Status.java
src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
src/main/java/com/wellcom/domain/Member/Member.java
src/main/java/com/wellcom/domain/Record/Record.java
src/main/java/com/wellcom/domain/Reservation/Reservation.java
src/main/java/com/wellcom/domain/Reservation/Status.java
src/main/java/com/wellcom/domain/SharingRoom/Controller/SharingRoomController.java
src/main/java/com/wellcom/domain/SharingRoom/Dto/SharingRoomCreateReqDto.java
src/main/java/com/wellcom/domain/SharingRoom/Dto/SharingRoomCreateResDto.java
src/main/java/com/wellcom/domain/SharingRoom/Repository/SharingRoomRepository.java
src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
src/main/java/com/wellcom/domain/SharingRoom/SharingRoom.java
src/main/java/com/wellcom/domain/common/CommonResponse.java
src/main/resources/application.yml

[ADD] domain별 Entity추가/Sharing Room 생성

---

src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
src/main/java/com/wellcom/domain/Desk/Desk.java
src/main/java/com/wellcom/domain/Desk/Dto/DeskCreateReqDto.java
src/main/java/com/wellcom/domain/Desk/Dto/DeskResDto.java
src/main/java/com/wellcom/domain/Desk/Dto/testDto.java
src/main/java/com/wellcom/domain/Desk/Repository/DeskRepository.java
src/main/java/com/wellcom/domain/Desk/Service/DeskService.java
src/main/java/com/wellcom/domain/Desk/Status.java
src/main/java/com/wellcom/domain/common/ExceptionHandlerClass.java
src/main/resources/application.yml

<br />
- Desk 생성, 전체 조회,  필터링 조회 API 구현
<br />
1. 새로운 Desk생성
- 입출력 예시
2. 테이블 전체 조회 및 필터링
- 입출력 예시(전체조회)
- 입출력 예시(필터링)
<br />
- ExceptionHandlerClass에 DataIntegrityViolationException에러 추가(엔티티의 칼럼이 Unique인 칼럼에 중복인 값을 넣으려고 시도할때 나오는 에러)

[ADD] Desk - Create/Read

---

src/main/java/com/wellcom/domain/SharingRoom/Controller/SharingRoomController.java

<br />
1. SharingRoom CRUD 수정
/rooms 만 인증 없이 접근 가능
나머지는 user/ 붙이면서 로그인 강제

[UPDATE] CRUD API 수정

---

src/main/java/com/wellcom/domain/SharingRoom/Dto/testDto.java
src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
src/main/java/com/wellcom/domain/SharingRoom/SharingRoom.java

<br />
1. 불필요한 testDto 삭제
2. delete 로직에서 DB에서 값을 지우는 것이 아닌 delYn을 "N" 값으로 세팅하도록 수정 -> 추후 기록 조회 가능

SharingRoom delYn 추가 및 delete 로직 수정

---

build.gradle
src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
src/main/java/com/wellcom/domain/SharingRoom/config/S3Config.java

<br />
- s3 이미지 처리
- 사용자 첨부 이미지 업로드 및 객체 URL 리턴
- 객체 URL DB저장
<br />
- postman에서 SharingRoom 생성 시 S3에 저장된 이미지의 URL 값 들어감
- S3 버킷에 정상 업로드
- 중복 파일 이름을 방지하기 위해 UUID + 원래 파일명 형식으로 삽입
- 링크 가져오면 업로드 했던 이미지 확인 가능

[ADD] Image Upload and getUrl To S3

---

src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
src/main/resources/application.yml

<br />
- s3 관련 설정 application-s3.yml로 분리

[UPDATE] Separate application-s3.yml

---

.gitignore

<br />
<br />
<br />
- application-s3.yml 파일 .gitignore 추가
<br />

[DELETE] S3 시크릿 키 .yml파일 삭제

---

src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
src/main/java/com/wellcom/global/error/ExceptionHandlerClass.java

<br />
1. update 시 지정된 폴더 안 이미지 경로를 저장 -> S3 객체 URL을 저장으로 수정
2. delete에는 주석 추가
3. 예외처리 로직 추가
(1) 자신이 생성하지 않은 SharingRoom에 수정 혹은 삭제 시 AccessDeniedException 발생
(2) 정해진 파일 업로드 용량(10MB) 초과한 이미지 업로드 시 MaxUploadSizeExceededException 발생

[UPDATE] update, delete 코드 수정 및 예외 처리로직 추가

---

front-end/src/components/SignInComponent.vue
front-end/src/components/SignUpComponent.vue
src/main/java/com/wellcom/domain/Member/Member.java

<br />
- 실행 오류 해결
<br />
1. 멤버 엔티티 수정
- NotNull 옵션 제외
2. 로그인 화면 비밀번호 마스킹 표시 오류 해결
- v-text-field input -> font-family 사용
<br />
- 멤버 엔티티 수정이 있어서 풀 받은 후 첫 실행 시 create로 먼저 돌린 후 다시 재 테스트 해야합니다.
<br />

[HOTFIX] 멤버 엔티티 수정 및 비밀번호 문자 표시 오류 해결

---

front-end/src/App.vue
front-end/src/components/MainFooter.vue

[ADD] Main Footer

---

front-end/src/router/index.js
front-end/src/views/TableHome.vue

[ADD] Table Reservation Page

---

front-end/src/router/index.js
front-end/src/views/MainLanding.vue
front-end/src/views/SharingHome.vue

[ADD] Main Landing Page, Sharing Page

---

front-end/src/views/MainLanding.vue

[FIX] 메인페이지 버튼 트랜지션 수정

---

front-end/src/views/MainLanding.vue

<br />
- 메인 페이지 버튼박스 및 내부 폰트 브라우저 사이즈별 반응형 사이즈 추가

[FIX] 메인페이지 사이즈 크기별 반응형 추가

---

src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
src/main/java/com/wellcom/domain/Desk/Desk.java
src/main/java/com/wellcom/domain/Desk/Dto/DeskUpdateReqDto.java
src/main/java/com/wellcom/domain/Desk/Service/DeskService.java
src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
src/main/java/com/wellcom/domain/Member/Dto/MemberUpdateReqDto.java
src/main/java/com/wellcom/domain/Member/Dto/ReservationDetailDto.java
src/main/java/com/wellcom/domain/Member/Member.java
src/main/java/com/wellcom/domain/Member/Service/MemberService.java

<br />
- 데스크 정보 수정하는 기능 추가
<br />
tv유무 , 테이블상태, 자리수 정보변경
<br />
<br />

[ADD] desk update 기능추가

---

front-end/src/router/index.js
front-end/src/router/sharingRouter.js
front-end/src/views/SharingHome.vue

<br />
1. SharingRoom 별도 Route 파일 js 추가
2. SharingRoom 메인 메이지인 SharingRoom 리스트 개발

[ADD] sharingRoom Router, sharingRoom List 구현

---

front-end/src/router/index.js
front-end/src/router/sharingRouter.js

<br />
1. 라우터 추가로 인한 메인페이지 에러 수정

[HOTFIX] sharingRoom Router추가로 인한 메인 에러 수정

---

front-end/src/views/SharingForm.vue
front-end/src/views/SharingRoomDetail.vue

[HOTFIX] sharingRoom Router추가로 인한 메인 에러 수정2

---

front-end/src/router/sharingRouter.js
front-end/src/views/SharingForm.vue
front-end/src/views/SharingHome.vue
front-end/src/views/SharingRoomDetail.vue

[ADD] sharingRoom 화면 개발

---

front-end/src/plugins/tokenPlugin.js
front-end/src/views/TableHome.vue

<br />
1. 테이블 즉시 사용등록버튼, 필터링 버튼 추가
- 테이블 죽시사용 구동확인
2. 테이블 조건 필터링 버튼 추가
3. 예약 모달 수정중

[FIX] 테이블 페이지 즉시사용버튼, 필터링 버튼 추가/ 예약 페이지 수정

---

front-end/src/components/AdminHomeForm.vue
src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java

<br />
- 관리자페이지추가
<br />
<br />
<br />

[ADD] admin page memberservice 구현

---

front-end/src/views/TableHome.vue
src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java

[FIX] 날짜계산로직수정

---

front-end/src/components/GoogleRedirect.vue
front-end/src/components/SignInComponent.vue
front-end/src/components/SignUpComponent.vue
src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
src/main/java/com/wellcom/domain/Member/Dto/MemberSignUpDto.java
src/main/java/com/wellcom/domain/Member/Service/MemberService.java
src/main/java/com/wellcom/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
src/main/java/com/wellcom/global/config/SecurityConfig.java
src/main/java/com/wellcom/global/socket/ChatController.java

<br />
- 소셜 로그인 페이징 처리
- 회원가입 모달 화면 처리 및 유효성 검사 추가
<br />
2. 로그인 데이터 처리
<br />
<br />

[ADD] 로그인 코드 수정 및 회원가입 화면 구성

---

front-end/src/views/NanumGameRoom.vue
src/main/java/com/wellcom/global/socket/ChatController.java
src/main/java/com/wellcom/global/socket/RoomNumber.java
src/main/java/com/wellcom/global/socket/UserGameData.java
src/main/java/com/wellcom/global/socket/WebSocketConfig.java

<br />
1. 각 SharingRoom을 눌렀을 때, 3명 인원이 들어오면 문제 출제
2. 게임에 참가한 Client들에게 0~랜덤 숫자 입력받아 (최대 1회), 중복을 제외한 가장 큰 숫자를 입력한 Client에게 "축하합니다" 메시지 전달. (나머지는 "탈락입니다")
<br />
< 구현 예정 사항 >
- 2번 기능이 서버 print.out에서는 잘 동작하는데, Client Session으로 값을 제대로 전달을 못해 각 Client마다 결과 값을 convertAndSend()으로 전달하는 로직에서 convertAndSend()로 전체 Client에게 동일한 결과 값(우승자) 전달로 로직 수정 예정
- "나가기" 버튼에 disconnect()로직을 구현해, 게임에서 나가 소켓 연결이 끊어진 경우 입장 인원 감소
- 방 마다 제한 인원으로 Client 접근 제한
- 실시간 방 접속 인원을 SharingRoom 목록에서 O / O 형식으로 확인 가능
- DB와 값 연동

[ADD] Game 로직 구현

---

front-end/src/views/TableHome.vue
src/main/java/com/wellcom/domain/Desk/Desk.java
src/main/java/com/wellcom/domain/Desk/Dto/DeskResDto.java

[ADD] 테이블 3d 효과 추가

---

front-end/src/App.vue
front-end/src/views/mypage.vue
src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java

[ADD] mypage frontend 구현

---

front-end/.env
front-end/src/components/SignInComponent.vue
front-end/src/views/NanumGameRoom.vue
src/main/java/com/wellcom/global/config/WebConfig.java
src/main/java/com/wellcom/global/email/controller/EmailController.java
src/main/java/com/wellcom/global/socket/ChatController.java
src/main/java/com/wellcom/global/socket/ChatPreHandler.java

[FIX] 회원 가입 중복 이메일 처리

---

front-end/src/views/NanumGameRoom.vue
front-end/src/views/SharingForm.vue
front-end/src/views/SharingHome.vue
front-end/src/views/SharingRoomDetail.vue
src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
src/main/java/com/wellcom/global/socket/ChatController.java

<br />
1. 상품 사진 등록하지 않아도 업로드 가능하게 백엔드 코드 수정
2. SharingRoom 상세조회 화면에서 수정 취소 기능 추가
<br />
구현할 점
- 수정 시 이미지 처리
- 문제 출제 시 \n 줄바꿈 출력 처리

[UPDATE] SharingRoomDetail 수정

---

front-end/src/views/AdminHomeForm.vue

[add] adminpage 구현

---

front-end/src/components/MainHeader.vue
front-end/src/views/mypage.vue

[FIX] 헤더에 어드민 페이지 추가

---

README.md

[UPDATE] README 수정

---

front-end/src/App.vue
front-end/src/components/MainFooter.vue
front-end/src/views/TableHome.vue
src/main/java/com/wellcom/domain/Desk/Dto/DeskResDto.java
src/main/java/com/wellcom/domain/Desk/Repository/DeskRepository.java
src/main/java/com/wellcom/domain/Desk/Service/DeskService.java
src/main/java/com/wellcom/domain/Reservation/Service/ReservationService.java

<br />
- 예약 취소 버튼 추가 및 예약자 본인 확인가능 표시
- 테이블 전체조회 성능 개선
<br />
1. 테이블 전체조회 성능 개선
- Fetch join 및 ReadOnly 사용으로 수정

[ADD] 프론트 예약취소 버튼 추가

---

src/main/java/com/wellcom/domain/Desk/Dto/DeskResDto.java
src/main/java/com/wellcom/domain/Reservation/Service/ReservationService.java
src/main/resources/application.yml

[FIX] 즉시예약로직 수정및 시간대 설정
